### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by Syedaslamsheikdawood** [INFO-523-Exercises/project-final-Pattern-Pioneers#11]
The following is the peer review of the Presentation proposal by MineCrafters. The team members that participated in this review are 

- Hari Dave - @haridave0718
- Sarthak Miglani - @sarthakMiglani726
- Partha Koundinya P - @partha-pkp
- Vinu Kevin Diesel - @Kevin-diesel-1194
- Syed Aslam Sheik Dawood - @Syedaslamsheikdawood

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes. The research question was well designed and the datas was used relavent to the researched question.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes, they used different barplots, correlation heatmap, and other visualization but didn't interpreted them. Other than that rest all were good in all perspective to visualize.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
Yes. the limitations were considered accordingly and we think that they would have spent even more time in planning and implementation of the project.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
Yes, the slides were well organized, readable, not full of text as we can see some graphs and plots as well and it got labels, legends etc in it.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
Yes. The team presentation was good and they sticked to their topic and didn't go off topic at any time, everyone in the team presented well and got chance to talk meaningful topic about the project.

**Comment by bharath03-a** [comment]
Thanks for the review!

Team Pattern Pioneers
