### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by poojithapasala** [INFO-523-Exercises/project-final-Pattern-Pioneers#12]
The following is the peer review of the Presentation proposal by The Algo-Rhythms. The team members that participated in this review are 

[Avikal Singh] - @avikalsingh1

[Himanshu Nimbarte] - @Himanshu200102

[Poojitha Pasala] - @poojithapasala

[Shakir Ahmed] - @Shakir0585

[Visalakshi Iyer] - @visalakshi2001

 ...

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Some slides were not interpreted well, someone pointed out an anomaly from a "histogram"

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
Yes critical thought is put into the project planning and it doesn't have any limitations

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
Slides were not organized perfectly. some text went out of the frame, and some slides were in the wrong position.
Text on the plots were unreadable. Dataset , Pre-processing slides were too long.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
Some slides were shown slower than required and some (like the plots) were read through faster.
The presentation style was a little casual, with the flow having continuity issues.
The modeling sections of the presentation were perfectly delivered.
Overall, the team effort looks good and well practiced.

**Comment by bharath03-a** [comment]
Thanks for the review!

Team Pattern Pioneers
