### ISSUE TITLE
Presentation feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/project-final-Pattern-Pioneers#13]
Dear Pattern Pioneers: Below is the score breakdown for your presentation. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Time management     | 2         |     1   |
| Professionalism | 2         |      2  |
| Teamwork | 3         |   3     |
| Slides | 3         |   2     |
| Creativity Critical Thought | 3 |3 |
| Content - Q1 | 6 | 4 |
| Content - Q2 | 6 |6 |
| Total    | 25        |    21    |

Feedback: 
Time management: Went over 10 minutes
Slides: I noticed at least one typo, so the slides needed to be better proofed.
Content: the histogram was not a normal distribution, you can't just say it would be without that peak. To prove this, you needed a q-q plot or Shapiro-Wilk test. Also, the bar plot cannot be a normal distribution because it was frequency. You would have to compare it with a binomial distribution or other discrete distribution.

**Comment by bharath03-a** [comment]
Thanks for the review Prof. @Gchism94, We will take the feedback and improve on it!

Team Pattern Pioneers
